default_platform(:android)

platform :android do
  desc "distribute app to Firebase"
  lane :distribute do |options|
    env = options[:env]

    apk_path = File.expand_path("../../app/build/outputs/apk/#{env}/release/app-#{env}-release.apk", __FILE__)

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_#{env.upcase}"],
      groups: "#{env}-release",

      android_artifact_type: "APK",
      apk_path: apk_path
    )
  end
end
